
version: "3"

services:
  app:
    build: .
    environment:
      - NODE_ENV=development
      - SELECTED_DB=$banco
    command: yarn dev
    ports:
      - "3333:3333"
    volumes:
      - ".:/usr/app"
      - "node-modules:/usr/app/node_modules"
    env_file: 
      - default.env

  database:
    image: mongo

  postgres_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: teste
      POSTGRES_DB: pokemondb1
    ports:
      - "5432:5432"
    volumes:
     - ./src/database/createdb.sh:/docker-entrypoint-initdb.d/createdb.sh
volumes:
  node-modules:

