
version: "3"

services:
  app:
    build: .
    environment:
      - NODE_ENV=development
    command: yarn dev
    ports:
      - "3333:3333"
    volumes:
      - ".:/usr/app"
      - "node-modules:/usr/app/node_modules"
    env_file: 
      - default.env

  database:
    image: mongo

volumes:
  node-modules:

